<?php
/**
 * Created by PhpStorm.
 * User: Laolu
 * Date: 01/04/2017
 * Time: 15:35
 */
$path_to_root = "../..";
include_once($path_to_root . "/ics/includes/data_checks.inc");
include_once($path_to_root . "/includes/data_checks.inc");
include_once($path_to_root . "/ics/includes/ui/ui_lists.inc");
include_once($path_to_root . "/includes/ui/ui_lists.inc");
include_once($path_to_root . "/includes/ui/ui_controls.inc");
include_once($path_to_root . "/includes/ui/ui_input.inc");
include_once($path_to_root . "/includes/ui/ui_msgs.inc");
include_once($path_to_root . "/includes/ui/ui_globals.inc");
include_once($path_to_root . "/includes/ui/ui_view.inc");
?>